### ISSUE TITLE
Seed identification API for Nachet frontend - updated

### ISSUE THREAD

**Issue by S-Khos** [ai-cfia/louis-db#1]
The purpose is to implement a seed wiki component for Nachet that is sourced from a JSON API that can be fetched on demand. I have pasted an example snippet of what the JSON format could look like below. The JSON can be generated by scraping the seed identification directory provided by the CFIA  (figure 1). In regards to the pictures provided on the website, a link to the image can also be provided in the JSON as well. The JSON would idly contain all seed species, distinguished by their scientific name.

![image](https://github.com/ai-cfia/louis-db/assets/19809069/910a74cb-95c0-4b27-9f7a-a2d6d76e8433)
_FIGURE 1_

```
[
    {
      "family": "Malvaceae",
      
      "common_name": "Velvetleaf",
      
      "duration_of_life_cycle": "Annual",
      
      "seed_or_fruit_type": "Seed",
      
      "identification_features":
       {
        "seed_length": "3.0 - 4.0 mm",
    
        "seed_width": "2.3 - 3.6 mm",
    
        "shape": "Heart-shaped seed with unequal lobes and a conspicuous notch at hilum end",
    
        "surface_texture": "Seed dull with minute reticulations and scattered tubercles,concentrated at the hilum",
    
        "colour": "Seed greyish brown with a lighter-coloured pubescence",
    
        "other_features": "Flap-like tissue covering the hilum may be present"
       },
       
       "images": [
        "https://inspection.canada.ca/DAM/DAM-plants-vegetaux/STAGING/images-images/invasive_plants_seed_factsheet_abutilon_theophrasti_01cnsh_1476382781946_eng.jpg",
        "https://inspection.canada.ca/DAM/DAM-plants-vegetaux/STAGING/images-images/invasive_plants_seed_factsheet_abutilon_theophrasti_01cnsh_1476382781946_eng.jpg" 
      ],
      
       "source": "https://inspection.canada.ca/plant-health/seeds/seed-testing-and-grading/seeds-identification/abutilon-theophrasti/eng/1472604373914/1472604374428"

    
    }
  ]
```

**Comment by rngadam** [comment]
This is the starting page where the list of seeds can be found:

https://inspection.canada.ca/plant-health/seeds/seed-testing-and-grading/seeds-identification/eng/1333136604307/1333136685768

**Comment by RussellJimmies** [comment]
Also, can you add this section to the "similar_species" key? I would display the info before showing the images.
![image](https://github.com/ai-cfia/louis-db/assets/88112401/3ddcb231-61cd-47e2-8a15-337bf6ed592a)

**Comment by JolanThomassin** [comment]
@RussellJimmies I've added it into the code, so now you'll have access to all the details regarding similar species as well as the source URLs.
