### ISSUE TITLE
Docker Container Initialization Error with louis-db

### ISSUE THREAD

**Issue by JolanThomassin** [ai-cfia/louis-db#13]
**Issue Description:**  
Error when trying to launch postgres.sh in louis-db-server.

**Steps to Reproduce:**  
1. Clone the `louis-db` repository.
2. Go to the branch `issue8-missing-chunks` to have access to the bin folder
3. Create a symbolic link to `~/src/louis-db/bin/postgres.sh` using the command: `ln -s ~/src/louis-db/bin/postgres.sh`.
4. Execute `./postgres.sh`.
5. Check the active Docker containers using `docker ps`.
6. Observe that the expected Docker container for louis-db is missing.
7. To investigate further, check the logs of the louis-db server with the command: `docker logs louis-db-server`.

**Error Message:**
```
chmod: /var/run/postgresql: Operation not permitted
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```
**Expected Behavior:**
The Docker container for louis-db should be created and initialized without errors.

**Operating System: Windows 10**
- Windows Subsystem for Linux (WSL) Version: 2
- WSL Distribution: Ubuntu
- Visual Studio Version: 1.82.0
- Docker Version: 24.0.5

**Comment by rngadam** [comment]
I've deleted my pgdata, emptied out my `.env` and reran it and was not able to reproduce. 

@JolanThomassin  can you give me the versions of postgres you have installed? 

```
ngadamr@QCMONTC701988P:~/src/louis-db$ docker images postgres
REPOSITORY   TAG         IMAGE ID       CREATED        SIZE
postgres     15-alpine   696ffaadb338   2 months ago   237MB
postgres     15.2        bf700010ce28   4 months ago   379MB
```

Maybe they updated something in later images?

Indeed:

```
ngadamr@QCMONTC701988P:~/src/louis-db/postgres$ docker  pull  postgres:15-alpine
15-alpine: Pulling from library/postgres
7264a8db6415: Pull complete
6ff36a0c8b9b: Pull complete
41485c1d4f30: Pull complete
b1c0fd40744e: Pull complete
c03dbaaa41b8: Pull complete
bef2a2546759: Pull complete
d80603666f21: Pull complete
b76686cd2926: Pull complete
Digest: sha256:8bc3c893342c766481df5fde58fab6f1a1115b94eb56778126163305243e9709
Status: Downloaded newer image for postgres:15-alpine
docker.io/library/postgres:15-alpine
ngadamr@QCMONTC701988P:~/src/louis-db/postgres$ docker images postgres
REPOSITORY   TAG         IMAGE ID       CREATED        SIZE
postgres     15-alpine   ab8fb914369e   3 weeks ago    237MB
postgres     <none>      696ffaadb338   2 months ago   237MB
postgres     15.2        bf700010ce28   4 months ago   379MB
```

however when I rebuild out of image ab8fb914369e it still works:

https://gist.github.com/rngadam/6c26377e82c0715e266b0f0cf45479dd

@JolanThomassin can you check the hash for your postgres:15-alpine ?

**Comment by JolanThomassin** [comment]
L'erreur que je rencontre pourrait provenir de mon installation de PostgreSQL.

Voici les versions de PostgreSQL que j'ai actuellement installées, ainsi que ma tentative de pull.

```
thomassinj@QCMONTC701529P:~/src/louis-db/postgres$ docker images postgres
REPOSITORY   TAG         IMAGE ID       CREATED       SIZE
postgres     15-alpine   ab8fb914369e   3 weeks ago   237MB

thomassinj@QCMONTC701529P:~/src/louis-db/postgres$ docker pull postgres:15-alpine
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 172.26.80.1:53: read udp 172.26.85.204:40495->172.26.80.1:53: i/o timeout
```

Je constate que nous avons le même hachage pour postgres:15-alpine. Cependant, est-il envisageable que ma tentative de pull ait été mal exécutée ? @rngadam

**Comment by rngadam** [comment]
non, si tu as le bon hash c'est que ça fonctionné dans le passé. l'erreur du daemon c'est dû à une connection actuelle réseau (tu es probablement sur VPN?)

**Comment by JolanThomassin** [comment]
Je confirme que je suis connecté au VPN.

![image](https://github.com/ai-cfia/louis-db/assets/98430140/639e4ae2-ef6e-41be-8861-3463be747761)

**Comment by JolanThomassin** [comment]
**Server Existence Check:**  
We first verified that the server already existed in our environment. This step was to ensure we didn't inadvertently create a duplicate instance.

**Server Stop and Removal:**  
Upon confirming the server's presence, we took the necessary action to stop and remove it. This step was essential for performing any subsequent modifications or updates to the server configuration.
```
docker stop louis-db-server
docker rm louis-db-server
```

**Restart Using postgres.sh:**  
After removing the existing server, we initiated its restart using the postgres.sh script.

___  
By executing these actions, we ensured the server was properly maintained, the necessary changes were made, and our environment was set up to function correctly with the updated configuration and environment variables. In the last commit ([7757421](https://github.com/ai-cfia/louis-db/commit/7757421042e1e503bb4a7b44c5e25f8f8916e4a8)), we included an 'echo' statement. This addition allows you to quickly determine whether the container already exists.

**Comment by JolanThomassin** [comment]
I've introduced a **verification function** in the last commit ([74d69c4](https://github.com/ai-cfia/louis-db/pull/14/commits/74d69c4b8d5bd3826842edd2c787c127e4e4ea64)) called `is_parameter_empty` in `lib.sh` to **validate parameters before their usage**. Currently, this function is implemented specifically for `PGPASSWORD` and `DB_SERVER_CONTAINER_NAME`.

**Comment by JolanThomassin** [comment]
I've applied modification on the **verification function** in the last commit ([0ce5846](https://github.com/ai-cfia/louis-db/pull/14/commits/0ce58462b6e69a8eb78f5d735c27c909b02fb48f)), now you can utilize the function to **validate all environment variables before their usage**, if any of them are undefined or empty, **the execution will stop**.
