### ISSUE TITLE
Create finesse-db python package to use in finesse-backend

### ISSUE THREAD

**Issue by melanie-fressard** [ai-cfia/louis-db#20]
Create a new Python function usable instead of match_documents. 
Should be benchmarked, and usable as a package.

**Comment by melanie-fressard** [comment]
To adress the delay in search function : issue #38

**Comment by rngadam** [comment]
I think the title of this should be "create finesse-db python package for use by finesse-backend" which is what @CFIALeronB will be working on next (after finishing up using test data in the frontend)

**Comment by melanie-fressard** [comment]
I was trying to come up with a good title but couldn't do it, thank you
